# Generated by Django 5.2.3 on 2025-06-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('booker', 'Event Booker'), ('poster', 'Event Poster'), ('admin', 'Admin')], default='booker', max_length=10),
        ),
    ]
